name: we_chat
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  google_sign_in: ^5.0.0
  cloud_firestore:  ^1.0.0
  firebase_messaging: ^9.0.0
  plugin_platform_interface: ^2.0.0
  firebase_storage: ^8.0.0
  image_picker: ^0.7.2
  shared_preferences: ^2.0.3
  intl: ^0.17.0
  modal_progress_hud: ^0.1.3
  splashscreen: ^1.3.5
  photo_view: ^0.10.2
  fluttertoast: ^7.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
  - images/
